# Generated by Django 3.1.2 on 2021-01-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=100, null=True)),
                ('body', models.TextField(max_length=200)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
