# Generated by Django 3.1.2 on 2021-01-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='entry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='key',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
