# Generated by Django 3.1.2 on 2021-01-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210117_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='subject',
            field=models.CharField(choices=[('chemistry', 'chemistry'), ('fauna', 'fauna'), ('biology', 'biology'), ('astronomy', 'astronomy'), ('machinery', 'machinery'), ('default', 'default')], default='default', max_length=200),
        ),
    ]
